[package]
name = "simply_shooter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.52"
bevy = "0.6.0"
ron = "0.7.0"
serde = "1.0.133"

[features]
